### ISSUE TITLE
multiple servers using 1 file causes race condition

### ISSUE THREAD

**Issue by nsturnitin** [maruf-freelancer/capistrano-deploy-lock#3]
this portion of the script would only allow for 1 file to be downloaded, yet this will fail with anything more than 1 server. :(

on roles(fetch(:deploy_lock_roles)).to_a, *\* in: :parallel*\*  do |host|
      if test("[ -f #{fetch(:deploy_lock_file)} ]")
        system "mkdir -p tmp"
        **download! fetch(:deploy_lock_file), "tmp/deploy-lock.yml"**
        output = File.read("tmp/deploy-lock.yml")
        system "rm -f tmp/deploy-lock.yml"
        if output && output != ""
          set :deploy_lock, YAML.load(output)

**Comment by nsturnitin** [comment]
here's what I changed it to:

# Read lock on remote host

`if test("[ -f #{fetch(:deploy_lock_file)} ]")
          output = capture "cat #{fetch(:deploy_lock_file)}"
          deploy_lock = YAML.load(output)
        else
          # no deploy lock was found on server
          next
        end`

**Comment by mhbcse** [comment]
Thanks for your valuable input. Solved the problem in version 1.0.3
