### ISSUE TITLE
Remove lock on deploy:failed

### ISSUE THREAD

**Issue by allaire** [maruf-freelancer/capistrano-deploy-lock#5]
I think this would be useful to remove the lock when a deploy failed. Anything I'm missing?

**Comment by mhbcse** [comment]
Good point. I will fix this.

**Comment by allaire** [comment]
@maruf-freelancer Cool let me know if you need help! Cool script, excited to put this in our project when these small tweaks will be out 👍

**Comment by mhbcse** [comment]
@allaire I have pushed the updates to version 1.0.4
Thanks for your support. If you found any more issues or improvement opportunities, please let me know. I will be happy to implement.

**Comment by allaire** [comment]
Awesome thanks @maruf-freelancer !
